import {
  Sun,
  Flower2,
  BookOpen,
  Palette,
  Globe,
  Heart,
  Tent,
  Handshake,
  Info,
  HelpCircle,
  PenLine,
  Building2,
  Phone,
  TreePine,
  Star,
  Target,
  GraduationCap,
  Shield,
  Lightbulb,
  Mic,
  HeartHandshake,
  Brain,
  Cross,
  ClipboardList,
  Calendar,
  BookMarked,
  Theater,
  FlaskConical,
  Baby,
  PartyPopper,
  MessageCircle,
  Users,
  Monitor,
  Bot,
  Music,
  Gamepad2,
  Ruler,
  Languages,
  FileText,
  Camera,
  MapPin,
  Search,
  Sprout,
  CheckCircle2,
  Award,
  Trophy,
  Utensils,
  Clock,
  Shirt,
  Dumbbell,
  Drama,
  Sparkles,
  Blocks,
  Brush,
  Footprints,
  type LucideIcon,
} from "lucide-react";

const iconMap = {
  sun: Sun,
  flower: Flower2,
  "book-open": BookOpen,
  palette: Palette,
  globe: Globe,
  heart: Heart,
  tent: Tent,
  handshake: Handshake,
  info: Info,
  "help-circle": HelpCircle,
  "pen-line": PenLine,
  building: Building2,
  phone: Phone,
  tree: TreePine,
  star: Star,
  target: Target,
  "graduation-cap": GraduationCap,
  shield: Shield,
  lightbulb: Lightbulb,
  mic: Mic,
  "heart-handshake": HeartHandshake,
  brain: Brain,
  cross: Cross,
  clipboard: ClipboardList,
  calendar: Calendar,
  "book-marked": BookMarked,
  theater: Theater,
  flask: FlaskConical,
  baby: Baby,
  "party-popper": PartyPopper,
  "message-circle": MessageCircle,
  users: Users,
  monitor: Monitor,
  bot: Bot,
  music: Music,
  gamepad: Gamepad2,
  ruler: Ruler,
  languages: Languages,
  "file-text": FileText,
  camera: Camera,
  "map-pin": MapPin,
  search: Search,
  sprout: Sprout,
  "check-circle": CheckCircle2,
  award: Award,
  trophy: Trophy,
  utensils: Utensils,
  clock: Clock,
  shirt: Shirt,
  dumbbell: Dumbbell,
  drama: Drama,
  sparkles: Sparkles,
  blocks: Blocks,
  brush: Brush,
  footprints: Footprints,
} as const;

export type IconName = keyof typeof iconMap;

interface IconProps {
  name: IconName;
  size?: number;
  className?: string;
  strokeWidth?: number;
}

export default function Icon({ name, size = 20, className = "", strokeWidth = 2 }: IconProps) {
  const LucideIcon: LucideIcon = iconMap[name];
  if (!LucideIcon) return null;
  return <LucideIcon size={size} className={className} strokeWidth={strokeWidth} />;
}

export { iconMap };
